#!/usr/bin/env python3
import argparse
import datetime as dt
import re
import sys
from pathlib import Path

STATUS_VALUES = {
    "not-started": "Not Yet Started",
    "in-progress": "Partially Taken",
    "completed": "Finished",
    "dropped": "Dropped",
}

ALLOWED_CATEGORIES = {"USER", "ACTION", "RESULT"}
REQUIRED_SECTIONS = [
    "Current Status",
    "Context",
    "Why It Is Needed",
    "Completion Criteria",
    "Detailed Plan",
    "Activity Log",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Update an existing TODO markdown file generated by create-todo skill. "
            "Updates status metadata and appends activity log entries."
        )
    )
    parser.add_argument("--file", required=True, help="Path to TODO markdown file")
    parser.add_argument(
        "--status",
        choices=tuple(STATUS_VALUES.keys()),
        help="New status value",
    )
    parser.add_argument(
        "--dropped-reason",
        help="Dropped reason when status is dropped (or update dropped reason)",
    )
    parser.add_argument(
        "--context",
        help="Replace entire Context section body",
    )
    parser.add_argument(
        "--why-needed",
        help="Replace entire Why It Is Needed section body",
    )
    parser.add_argument(
        "--completion-criteria",
        help="Replace entire Completion Criteria section body",
    )
    parser.add_argument(
        "--detailed-plan",
        help="Replace entire Detailed Plan section body",
    )
    parser.add_argument(
        "--pseudo-code-diff",
        help="Replace the Pseudo Code Diff section body",
    )
    parser.add_argument(
        "--user-note",
        help="Append USER activity log entry",
    )
    parser.add_argument(
        "--action-note",
        help="Append ACTION activity log entry",
    )
    parser.add_argument(
        "--result-note",
        help="Append RESULT activity log entry",
    )
    parser.add_argument(
        "--log",
        nargs=2,
        action="append",
        metavar=("CATEGORY", "DETAIL"),
        help="Append a log entry; category must be USER|ACTION|RESULT",
    )
    return parser.parse_args()


def split_sections(content: str) -> tuple[str, dict[str, str]]:
    title_match = re.search(r"(?m)^# TODO: .+$", content)
    if not title_match:
        raise ValueError("missing title line '# TODO: ...'")

    title_line = title_match.group(0)

    headings: list[tuple[str, int, int]] = []
    offset = 0
    fence_marker = ""
    fence_length = 0
    for line in content.splitlines(keepends=True):
        fence = re.match(r"^ {0,3}(`{3,}|~{3,})(.*)$", line.rstrip("\r\n"))
        if fence_marker:
            if (
                fence
                and fence.group(1)[0] == fence_marker
                and len(fence.group(1)) >= fence_length
                and not fence.group(2).strip()
            ):
                fence_marker = ""
        elif fence:
            fence_marker = fence.group(1)[0]
            fence_length = len(fence.group(1))
        elif line.startswith("## "):
            headings.append((line[3:].strip(), offset, offset + len(line)))
        offset += len(line)

    sections: dict[str, str] = {}
    for index, (name, _, body_start) in enumerate(headings):
        if name in sections:
            raise ValueError(f"duplicate section: {name}")
        body_end = headings[index + 1][1] if index + 1 < len(headings) else len(content)
        sections[name] = content[body_start:body_end].rstrip("\n")

    missing = [name for name in REQUIRED_SECTIONS if name not in sections]
    if missing:
        raise ValueError(f"missing required sections: {', '.join(missing)}")

    return title_line, sections


def parse_status_block(block: str) -> dict[str, str]:
    state = ""
    dropped_reason = ""
    last_status_update = ""

    for line in block.splitlines():
        if line.startswith("- State:"):
            state = line.split(":", 1)[1].strip()
        elif line.startswith("- Dropped Reason:"):
            dropped_reason = line.split(":", 1)[1].strip()
        elif line.startswith("- Last Status Update:"):
            last_status_update = line.split(":", 1)[1].strip()

    if not state or not last_status_update:
        raise ValueError("invalid 'Current Status' block")

    return {
        "state": state,
        "dropped_reason": dropped_reason,
        "last_status_update": last_status_update,
    }


def format_status_block(state: str, dropped_reason: str, last_status_update: str) -> str:
    return "\n".join(
        [
            f"- State: {state}",
            f"- Dropped Reason: {dropped_reason}",
            f"- Last Status Update: {last_status_update}",
        ]
    )


def normalize_detail(value: str) -> str:
    return " ".join(value.strip().split())


def build_log_entries(args: argparse.Namespace, timestamp: str, target: Path) -> list[str]:
    entries: list[tuple[str, str]] = []

    if args.user_note:
        entries.append(("USER", args.user_note))
    if args.action_note:
        entries.append(("ACTION", args.action_note))
    if args.result_note:
        entries.append(("RESULT", args.result_note))

    if args.log:
        for category, detail in args.log:
            category = category.strip().upper()
            if category not in ALLOWED_CATEGORIES:
                raise ValueError(
                    f"invalid log category '{category}'; expected USER, ACTION, or RESULT"
                )
            entries.append((category, detail))

    if not entries:
        entries = [
            ("ACTION", "Updated TODO item via update_todo.py"),
            ("RESULT", f"TODO item updated at {target}"),
        ]

    return [
        f"- [{timestamp}] [{category}] {normalize_detail(detail)}"
        for category, detail in entries
    ]


def rebuild_markdown(title_line: str, sections: dict[str, str]) -> str:
    parts = [title_line, ""]
    for name, section_body in sections.items():
        body = section_body.rstrip("\n")
        parts.append(f"## {name}")
        parts.append(body)
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    args = parse_args()
    target = Path(args.file)

    if not target.exists() or not target.is_file():
        print(f"todo file not found: {target}", file=sys.stderr)
        return 1

    content = target.read_text(encoding="utf-8")

    try:
        title_line, sections = split_sections(content)
        status_info = parse_status_block(sections["Current Status"])
    except ValueError as exc:
        print(f"failed to parse todo file: {exc}", file=sys.stderr)
        return 1

    now = dt.datetime.now().replace(microsecond=0)
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")

    changed = False

    if args.status:
        status_info["state"] = STATUS_VALUES[args.status]
        changed = True

    if args.dropped_reason is not None:
        status_info["dropped_reason"] = args.dropped_reason.strip()
        changed = True

    if status_info["state"] == STATUS_VALUES["dropped"] and not status_info["dropped_reason"]:
        print(
            "dropped reason is required when state is 'Dropped'",
            file=sys.stderr,
        )
        return 1

    if status_info["state"] != STATUS_VALUES["dropped"] and args.status is not None:
        status_info["dropped_reason"] = ""

    if changed:
        status_info["last_status_update"] = timestamp
        sections["Current Status"] = format_status_block(
            status_info["state"],
            status_info["dropped_reason"],
            status_info["last_status_update"],
        )

    if args.context is not None:
        sections["Context"] = args.context.strip()
        changed = True
    if args.why_needed is not None:
        sections["Why It Is Needed"] = args.why_needed.strip()
        changed = True
    if args.completion_criteria is not None:
        sections["Completion Criteria"] = args.completion_criteria.strip()
        changed = True
    if args.detailed_plan is not None:
        sections["Detailed Plan"] = args.detailed_plan.strip()
        changed = True
    if args.pseudo_code_diff is not None:
        if "Pseudo Code Diff" not in sections:
            # Insert before the log without rearranging existing sections.
            ordered_sections = {}
            for name, body in sections.items():
                if name == "Activity Log":
                    ordered_sections["Pseudo Code Diff"] = ""
                ordered_sections[name] = body
            sections = ordered_sections
        sections["Pseudo Code Diff"] = args.pseudo_code_diff.strip()
        changed = True

    try:
        new_log_lines = build_log_entries(args, timestamp, target)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    existing_log = sections["Activity Log"].strip()
    log_parts = [existing_log] if existing_log else []
    log_parts.extend(new_log_lines)
    sections["Activity Log"] = "\n".join(log_parts)

    if not changed and not new_log_lines:
        print("no updates requested", file=sys.stderr)
        return 1

    output = rebuild_markdown(title_line, sections)
    target.write_text(output, encoding="utf-8")
    print(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
